[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["tests/"]
asyncio_mode = "auto"
markers = [
    "performance: marks tests as performance tests",
    "integration: marks tests as integration tests"
]

env = [
    "SERVER_NAME=Organization Test",
    "SERVER_HOST=http://localhost:6000",
    "ROUTER_URL=http://localhost:7000",
    "MONGO_HOST=localhost",
    "MONGO_USER=testuser",
    "MONGO_PASSWORD=mypassword",
    "MONGO_DB=organization",
    "MONGO_PORT=27017",
    "SUPERTOKENS_CONNECTION_URI=http://localhost:3569",
    "SUPERTOKENS_API_KEY=",
    "LOG_LEVEL=ERROR"
]

[tool.ruff]
line-length = 120
target-version = "py312"
